language: java
branches:
  only:
  - master
  - develop
before_install:
- chmod +x gradlew
install: true
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/install-oracle-jdk6.sh
- $HOME/build-script/travis-ci/nablarch-build.sh
- $HOME/build-script/travis-ci/upload-test-report.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  slack:
    secure: Q5qdVN1NYT5nzBJ8J6yeP337/TGWzOpvMw9U3azEfL8OnVWpIELyCJwMD4oYUvhuHY1BM952HXaz59HABAIW+i6wrTIL9tjEVEbvSNhbCQgE3VUSmkYolSJi9yduESCLpfCRxb+1jZyOCBn5LokN31N8j5RvxTOxbhekQ4Ia4UZxjl3IEuScOdjHNnKWxzXFGmhU/1p3veOwFXxobsrVP7QSkLaGw45Grg90c2r8bEFbo10dO1i+bbME0En6he+ZmoOsmmiVyDzvD8yASOcSR/W1N8ZF9nEZDTOYkys6nrDrX6rZHrPZpZoxM2vAG+iCEKXeBekgWO4ofGTTEZQSQCq33IiJy9v3oh+6fP9++Iha7NQ8cbeR3tGd1hQgeKSMIDnlUudi9xLU2CKUWUaUL+0NgKfC29zWiVBl+02jYvAw1JjzCdLCkClfVbUMp9wNYzOp7WpF24cmR0QqrQ3pkepHIuAP2IByP5pa3muGtuKLXw5lRNh7sf6xLL2lZWG+AwjWJsYL/13TLulBCBd2AYt0UCRCRtVSU8tX41Zd9lMxeT6j6QzK3+/G97Dhx35rcPdPo0irR1sMGNESghKW6QYeyjrFK4UuZJ245UToBqP9yfPa7SgKkjn2QjUFMDz9jtzmKp1XHSRYa0wgCQ2pIY+4l7hNCt+rLvSxB6t0+kY=
